import { MigrationInterface, QueryRunner } from 'typeorm';

// Generated reference data used by the one-time TypeORM migration.
// prettier-ignore
export const BANK_REFERENCE_DATA = [
  ["ASCBVNVX","Ngân hàng Á Châu","ACB"],
  ["ABBKVNVX","Ngân hàng An Bình","ABBANK"],
  ["ANZBVNVX","Ngân hàng ANZ Việt Nam","ANZVL"],
  ["NASCVNVX","Ngân hàng Bắc Á","Bac A Bank"],
  ["VCBCVNVX","Ngân hàng Bản Việt","BVBank"],
  ["BVBVVNVX","Ngân hàng Bảo Việt","BAOVIET Bank"],
  ["CIBBVNVN","Ngân hàng CIMB Việt Nam","CIMB"],
  ["ICBVVNVX","Ngân hàng Công thương Việt Nam","VietinBank"],
  ["WBVNVNVX","Ngân hàng Đại Chúng Việt Nam","PVcomBank"],
  ["GBNKVNVX","Ngân hàng Dầu khí toàn cầu","GPBank"],
  ["BIDVVNVX","Ngân hàng Đầu tư và Phát triển Việt Nam","BIDV"],
  ["SEAVVNVX","Ngân hàng Đông Nam Á","SeABank"],
  ["MCOBVNVX","Ngân hàng Hàng Hải","MSB"],
  ["HLBBVNVX","Ngân hàng Hong Leong Việt Nam","HLBVN"],
  ["HSBCVNVX","Ngân hàng HSBC Việt Nam","HSBC"],
  ["IABBVNVX","Ngân hàng Indovina","IVB"],
  ["KLBKVNVX","Ngân hàng Kiên Long","Kienlongbank"],
  ["VTCBVNVX","Ngân hàng Kỹ Thương","Techcombank"],
  ["LVBKVNVX","Ngân hàng Lộc Phát Việt Nam","LVBank"],
  ["NAMAVNVX","Ngân hàng Nam Á","Nam A Bank"],
  ["GTBAVNVX","Ngân hàng Ngoại thương Công nghệ số","VCBNeo"],
  ["BFTVVNVX","Ngân hàng Ngoại Thương Việt Nam","Vietcombank"],
  ["VBAAVNVX","Ngân hàng NN&PT Nông thôn Việt Nam","Agribank"],
  ["HDBCVNVX","Ngân hàng Phát triển TPHồ Chí Minh","HDBank"],
  ["ORCOVNVX","Ngân hàng Phương Đông","OCB"],
  ["VIDPVNV5","Ngân hàng Public Bank Việt Nam","PBVN"],
  ["MSCBVNVX","Ngân hàng Quân Đội","MB"],
  ["NVBAVNVX","Ngân hàng Quốc dân","NCB"],
  ["VNIBVNVX","Ngân hàng Quốc Tế","VIB"],
  ["SHBAVNVX","Ngân hàng Sài Gòn - Hà Nội","SHB"],
  ["SACLVNVX","Ngân hàng Sài Gòn","SCB"],
  ["SBITVNVX","Ngân hàng Sài Gòn Công Thương","SAIGONBANK"],
  ["SGTTVNVX","Ngân hàng Sài Gòn Thương Tín","Sacombank"],
  ["SHBKVNVX","Ngân hàng Shinhan Việt Nam","SHBVN"],
  ["EACBVNVX","Ngân hàng Số Vikki","Vikki Bank"],
  ["SCBLVNVX","Ngân hàng Standard Chartered Việt Nam","SCBVL"],
  ["PGBLVNVX","Ngân hàng Thịnh vượng và Phát triển","PGBank"],
  ["TPBVVNVX","Ngân hàng Tiên Phong","TPBank"],
  ["UOVBVNVX","Ngân hàng UOB Việt Nam","UOB"],
  ["VRBAVNVX","Ngân hàng Việt - Nga","VRB"],
  ["VNTTVNVX","Ngân hàng Việt Á","VietABank"],
  ["OJBAVNVX","Ngân hàng Việt Nam Hiện Đại","MBV"],
  ["VPBKVNVX","Ngân hàng Việt Nam Thịnh Vượng","VPBank"],
  ["VNACVNVX","Ngân hàng Việt Nam Thương Tín","Vietbank"],
  ["HVBKVNVX","Ngân hàng Woori Việt Nam","Woori"],
  ["EBVIVNVX","Ngân hàng Xuất Nhập Khẩu","Eximbank"],
] as const;

// prettier-ignore
export const MCC_REFERENCE_DATA = [
  ["0742","Veterinary Services","Miscellaneous shops",true,"VM"],
  ["0763","Agricultural Cooperatives","Miscellaneous shops",true,"VM"],
  ["0780","Horticultural and Landscaping Services","Miscellaneous shops",true,"VM"],
  ["1520","General Contractors–Residential and Commercial","Miscellaneous shops",true,"VM"],
  ["1711","Air Conditioning, Heating and Plumbing Contractors","Miscellaneous shops",true,"VM"],
  ["1731","Electrical Contractors","Miscellaneous shops",true,"VM"],
  ["1740","Insulation, Masonry, Plastering, Stonework and Tile Setting Contractors","Miscellaneous shops",true,"VM"],
  ["1750","Carpentry Contractors","Miscellaneous shops",true,"VM"],
  ["1761","Roofing and Siding, Sheet Metal Work Contractors","Miscellaneous shops",true,"VM"],
  ["1771","Concrete Work Contractors","Miscellaneous shops",true,"VM"],
  ["1799","Contractors, Special Trade Contractors–not elsewhere classified","Miscellaneous shops",true,"VM"],
  ["2741","Miscellaneous Publishing and Printing","Miscellaneous shops",true,"VM"],
  ["2791","Typesetting, Plate Making and Related Services","Miscellaneous shops",true,"VM"],
  ["2842","Sanitation, Polishing and Specialty Cleaning Preparations","Miscellaneous shops",true,"VM"],
  ["3000","United Airlines","Transportation services",true,"VM"],
  ["3001","American Airlines","Transportation services",true,"VM"],
  ["3002","Pan American","Miscellaneous shops",true,"VM"],
  ["3003","Eurofly","Miscellaneous shops",true,"VM"],
  ["3004","Dragon Airlines","Transportation services",true,"VM"],
  ["3005","British Airways","Miscellaneous shops",true,"VM"],
  ["3006","Japan Air Lines","Miscellaneous shops",true,"VM"],
  ["3007","Air France","Miscellaneous shops",true,"VM"],
  ["3008","Lufthansa German Airlines","Transportation services",true,"VM"],
  ["3009","Air Canada","Miscellaneous shops",true,"VM"],
  ["3010","Royal Dutch Airlines (KLM Airlines)","Transportation services",true,"VM"],
  ["3011","Aeroflot","Miscellaneous shops",true,"VM"],
  ["3012","Qantas","Miscellaneous shops",true,"VM"],
  ["3013","Alitalia","Miscellaneous shops",true,"VM"],
  ["3014","Saudi Arabian Airlines","Transportation services",true,"VM"],
  ["3015","Swiss International Air Lines","Miscellaneous shops",true,"VM"],
  ["3016","Scandinavian Airline System (SAS)","Miscellaneous shops",true,"VM"],
  ["3017","South African Airways","Miscellaneous shops",true,"VM"],
  ["3018","Varig","Miscellaneous shops",true,"VM"],
  ["3019","Germanwings","Miscellaneous shops",true,"TSYS"],
  ["3020","Air India","Miscellaneous shops",true,"VM"],
  ["3021","Air Algerie","Miscellaneous shops",true,"VM"],
  ["3022","Philippine Airlines","Transportation services",true,"VM"],
  ["3023","Mexicana","Miscellaneous shops",true,"VM"],
  ["3024","Pakistan International","Miscellaneous shops",true,"VM"],
  ["3025","Air New Zealand Ltd. International","Miscellaneous shops",true,"VM"],
  ["3026","Emirates Airlines","Transportation services",true,"VM"],
  ["3027","Union De Transports Aeriens (UTA/interair)","Transportation services",true,"VM"],
  ["3028","Air Malta","Miscellaneous shops",true,"VM"],
  ["3029","SN Brussels Airlines","Transportation services",true,"VM"],
  ["3030","Aerolineas Argentinas","Miscellaneous shops",true,"VM"],
  ["3031","Olympic Airways","Miscellaneous shops",true,"VM"],
  ["3032","El Al","Miscellaneous shops",true,"VM"],
  ["3033","Ansett Airlines","Transportation services",true,"VM"],
  ["3034","Etihadair","Miscellaneous shops",true,"VM"],
  ["3035","TAP Air Portugal (TAP)","Miscellaneous shops",true,"VM"],
  ["3036","Viacao Aerea Sao Pãulo (VASP)","Miscellaneous shops",true,"VM"],
  ["3037","Egyptair","Miscellaneous shops",true,"VM"],
  ["3038","Kuwait Airways","Miscellaneous shops",true,"VM"],
  ["3039","Avianca","Miscellaneous shops",true,"VM"],
  ["3040","Gulf Air (Bahrain)","Miscellaneous shops",true,"VM"],
  ["3041","Balkan-Bulgarian Airlines","Transportation services",true,"VM"],
  ["3042","Finnair","Miscellaneous shops",true,"VM"],
  ["3043","Aer Lingus","Miscellaneous shops",true,"VM"],
  ["3044","Air Lanka","Miscellaneous shops",true,"VM"],
  ["3045","Nigeria Airways","Miscellaneous shops",true,"VM"],
  ["3046","Cruzeiro Do Sul","Miscellaneous shops",true,"VM"],
  ["3047","Turk Hava Yollari","Miscellaneous shops",true,"VM"],
  ["3048","Royal Air Maroc","Miscellaneous shops",true,"VM"],
  ["3049","Tunis Air","Miscellaneous shops",true,"VM"],
  ["3050","Icelandair","Miscellaneous shops",true,"VM"],
  ["3051","Austrian Airlines","Transportation services",true,"VM"],
  ["3052","LAN Airlines","Transportation services",true,"VM"],
  ["3053","Aviacion Y Comercio (AVIACO)","Miscellaneous shops",true,"VM"],
  ["3054","Linea Aerea Del Cobre (LADECO)","Miscellaneous shops",true,"VM"],
  ["3055","Lloyd Aero Boliviano (LAB)","Miscellaneous shops",true,"VM"],
  ["3056","Jet Airways","Miscellaneous shops",true,"VM"],
  ["3057","Virgin America","Miscellaneous shops",true,"VM"],
  ["3058","Delta","Miscellaneous shops",true,"VM"],
  ["3059","DBA Airline","Miscellaneous shops",true,"VM"],
  ["3060","Northwest Airlines","Transportation services",true,"VM"],
  ["3061","Continental","Miscellaneous shops",true,"VM"],
  ["3062","Hapag-Lloyd Express","Miscellaneous shops",true,"VM"],
  ["3063","US Airways","Miscellaneous shops",true,"VM"],
  ["3064","Adria Airways","Miscellaneous shops",true,"VM"],
  ["3065","Airinter","Miscellaneous shops",true,"VM"],
  ["3066","Southwest Airlines","Transportation services",true,"VM"],
  ["3067","Vanguard Airlines","Transportation services",true,"VM"],
  ["3068","Air Astana","Miscellaneous shops",true,"VM"],
  ["3069","Sun Country Airlines","Transportation services",true,"VM"],
  ["3071","Air British Columbia","Miscellaneous shops",true,"VM"],
  ["3072","Cebu Pacific Airlines","Transportation services",true,"VM"],
  ["3075","Singapore Airlines","Transportation services",true,"VM"],
  ["3076","Aeromexico","Miscellaneous shops",true,"VM"],
  ["3077","Thai Airways","Miscellaneous shops",true,"VM"],
  ["3078","China Airlines","Transportation services",true,"VM"],
  ["3079","Jetstar Airways","Miscellaneous shops",true,"VM"],
  ["3081","NordAir","Miscellaneous shops",true,"TSYS"],
  ["3082","Korean Airlines","Transportation services",true,"VM"],
  ["3083","Air Afrique","Miscellaneous shops",true,"VM"],
  ["3084","Eva Airways","Miscellaneous shops",true,"VM"],
  ["3085","Midwest Express Airlines","Transportation services",true,"VM"],
  ["3086","Carnival Airlines","Transportation services",true,"V"],
  ["3087","Metro Airlines","Transportation services",true,"VM"],
  ["3088","Croatia Air","Miscellaneous shops",true,"VM"],
  ["3089","Transaero","Miscellaneous shops",true,"VM"],
  ["3090","Uni Airways Corporation","Miscellaneous shops",true,"VM"],
  ["3094","Zambia Airways","Miscellaneous shops",true,"VM"],
  ["3096","Air Zimbabwe Corp","Miscellaneous shops",true,"VM"],
  ["3097","Spanair","Miscellaneous shops",true,"VM"],
  ["3098","Asiana Airlines","Transportation services",true,"VM"],
  ["3099","Cathay Pacific","Miscellaneous shops",true,"VM"],
  ["3100","Malaysian Airline System","Miscellaneous shops",true,"VM"],
  ["3102","Iberia","Miscellaneous shops",true,"VM"],
  ["3103","Garuda","Miscellaneous shops",true,"VM"],
  ["3106","Braathens S.A.F.E.","Miscellaneous shops",true,"VM"],
  ["3110","Wings Airways","Miscellaneous shops",true,"V"],
  ["3111","British Midland","Miscellaneous shops",true,"VM"],
  ["3112","Windward Island","Miscellaneous shops",true,"VM"],
  ["3115","Tower Air","Miscellaneous shops",true,"VM"],
  ["3117","Venezolana International De Aviacion","Miscellaneous shops",true,"VM"],
  ["3118","Valley Airlines","Transportation services",true,"VM"],
  ["3125","Tan Sahsa","Miscellaneous shops",true,"VM"],
  ["3126","Talair PTY Ltd.","Miscellaneous shops",true,"V"],
  ["3127","Taca International","Miscellaneous shops",true,"VM"],
  ["3129","Surinam Airways","Miscellaneous shops",true,"VM"],
  ["3130","Sunworld International","Miscellaneous shops",true,"VM"],
  ["3131","VLM Airlines","Transportation services",true,"VM"],
  ["3132","Frontier Airlines","Transportation services",true,"VM"],
  ["3133","Sunbelt Airlines","Transportation services",true,"V"],
  ["3135","Sudan Airways","Miscellaneous shops",true,"V"],
  ["3136","Qatar Airways","Miscellaneous shops",true,"VM"],
  ["3137","Singleton","Miscellaneous shops",true,"V"],
  ["3138","Simmons Airlines","Transportation services",true,"V"],
  ["3143","Scenic Airlines","Transportation services",true,"V"],
  ["3144","Virgin Atlantic","Miscellaneous shops",true,"VM"],
  ["3145","San Juan","Miscellaneous shops",true,"V"],
  ["3146","Luxair","Miscellaneous shops",true,"VM"],
  ["3148","Air Littoral S.A.","Miscellaneous shops",true,"VM"],
  ["3151","Air Zaire","Miscellaneous shops",true,"VM"],
  ["3154","Princeville","Miscellaneous shops",true,"V"],
  ["3156","Go Fly Ltd.","Miscellaneous shops",true,"VM"],
  ["3159","Provincetown-Boston Airways","Miscellaneous shops",true,"VM"],
  ["3161","All Nipon Airways","Miscellaneous shops",true,"VM"],
  ["3164","Norontair","Miscellaneous shops",true,"VM"],
  ["3165","New York Helicopter","Miscellaneous shops",true,"V"],
  ["3167","Aero Continente","Miscellaneous shops",true,"VM"],
  ["3170","Mount Cook","Miscellaneous shops",true,"V"],
  ["3171","Canadian Airlines International","Transportation services",true,"VM"],
  ["3172","Nationair","Miscellaneous shops",true,"VM"],
  ["3174","Jetblue Airways","Miscellaneous shops",true,"VM"],
  ["3175","Middle East Air","Miscellaneous shops",true,"VM"],
  ["3176","Metroflight Airlines","Transportation services",true,"V"],
  ["3177","AirTran Airways","Miscellaneous shops",true,"VM"],
  ["3178","Mesa Air","Miscellaneous shops",true,"VM"],
  ["3180","Westjet Airlines","Transportation services",true,"VM"],
  ["3181","Malev","Miscellaneous shops",true,"VM"],
  ["3182","LOT (Polish Airlines)","Transportation services",true,"VM"],
  ["3183","Oman Air","Miscellaneous shops",true,"VM"],
  ["3184","LIAT","Miscellaneous shops",true,"VM"],
  ["3185","Linea Aeropostal Venezolana (LAV)","Miscellaneous shops",true,"VM"],
  ["3186","Lineas Aereas Paraguayas (LAP)","Miscellaneous shops",true,"VM"],
  ["3187","LACSA (Costa Rica)","Miscellaneous shops",true,"VM"],
  ["3188","Virgin Express","Miscellaneous shops",true,"VM"],
  ["3190","Jugoslav Air","Miscellaneous shops",true,"VM"],
  ["3191","Island Airlines","Transportation services",true,"VM"],
  ["3193","Indian Airlines","Transportation services",true,"VM"],
  ["3196","Hawaiian Air","Miscellaneous shops",true,"VM"],
  ["3197","Havasu Airlines","Transportation services",true,"VM"],
  ["3200","Guyana Airways","Miscellaneous shops",true,"VM"],
  ["3203","Golden Pacific Air","Miscellaneous shops",true,"V"],
  ["3204","Freedom Airlines","Transportation services",true,"VM"],
  ["3206","China Eastern Airlines","Transportation services",true,"VM"],
  ["3211","Norwegian Air Shuttle","Miscellaneous shops",true,"VM"],
  ["3212","Dominicana De Aviacion","Miscellaneous shops",true,"VM"],
  ["3213","Malmo Aviation","Miscellaneous shops",true,"VM"],
  ["3215","Dan Air Services","Miscellaneous shops",true,"V"],
  ["3216","Cumberland Airlines","Transportation services",true,"V"],
  ["3217","Ceskoslovenske Aerolinie (CSA)","Miscellaneous shops",true,"VM"],
  ["3218","Crown Air","Miscellaneous shops",true,"V"],
  ["3219","Compania Panamena De Aviacion (COPA)","Miscellaneous shops",true,"VM"],
  ["3220","Compania Faucett","Miscellaneous shops",true,"VM"],
  ["3221","Transportes Aeros Militares","Transportation services",true,"VM"],
  ["3222","Command Airways","Miscellaneous shops",true,"VM"],
  ["3223","Comair","Miscellaneous shops",true,"VM"],
  ["3226","Skyways","Miscellaneous shops",true,"VM"],
  ["3228","Cayman Airways","Miscellaneous shops",true,"VM"],
  ["3229","SAETA (Sociedad Ecuatorianos De Transportes Aereos)","Transportation services",true,"VM"],
  ["3231","SAHSA (Servicio Aero De Honduras)","Miscellaneous shops",true,"VM"],
  ["3233","Capitol Air","Miscellaneous shops",true,"V"],
  ["3234","Caribbean Airlines","Transportation services",true,"VM"],
  ["3235","Brockway Air","Miscellaneous shops",true,"V"],
  ["3236","Air Arabia Airline","Miscellaneous shops",true,"VM"],
  ["3238","Bemidji Aviation","Miscellaneous shops",true,"V"],
  ["3239","Bar Harbor Airlines","Transportation services",true,"VM"],
  ["3240","Bahamasair","Miscellaneous shops",true,"VM"],
  ["3241","Aviateca","Miscellaneous shops",true,"VM"],
  ["3242","Avensa","Miscellaneous shops",true,"VM"],
  ["3243","Austrian Air Service","Miscellaneous shops",true,"VM"],
  ["3245","Easyjet Air","Miscellaneous shops",true,"VM"],
  ["3246","Ryanair","Miscellaneous shops",true,"VM"],
  ["3247","Gol Airlines","Transportation services",true,"VM"],
  ["3248","Tam Airlines","Transportation services",true,"VM"],
  ["3251","Aloha Airlines","Transportation services",true,"V"],
  ["3252","Antilean Airlines (ALM)","Transportation services",true,"VM"],
  ["3253","America West","Miscellaneous shops",true,"M"],
  ["3254","U.S. Air Shuttle","Miscellaneous shops",true,"V"],
  ["3256","Alaska Airlines Inc.","Transportation services",true,"VM"],
  ["3259","American Trans Air","Miscellaneous shops",true,"V"],
  ["3260","Spirit Airlines","Transportation services",true,"VM"],
  ["3261","Air China","Miscellaneous shops",true,"VM"],
  ["3262","Reno Air","Miscellaneous shops",true,"V"],
  ["3263","Aero Servicio Carabobo","Miscellaneous shops",true,"VM"],
  ["3266","Air Seychelles","Miscellaneous shops",true,"VM"],
  ["3267","Air Panama International","Miscellaneous shops",true,"VM"],
  ["3273","Rica Hotels","Transportation services",true,"TSYS"],
  ["3274","Inter Nor Hotels","Transportation services",true,"TSYS"],
  ["3280","Air Jamaica","Miscellaneous shops",true,"VM"],
  ["3281","Air Djibouti","Miscellaneous shops",true,"TSYS"],
  ["3282","Air Djibouti","Miscellaneous shops",true,"VM"],
  ["3284","Aero Virgin Islands","Miscellaneous shops",true,"V"],
  ["3285","Aero Peru","Miscellaneous shops",true,"VM"],
  ["3286","Aero Nicaraguensis","Miscellaneous shops",true,"VM"],
  ["3287","Aero Coach Aviation","Miscellaneous shops",true,"VM"],
  ["3292","Cyprus Airways","Miscellaneous shops",true,"VM"],
  ["3293","Ecuatoriana","Miscellaneous shops",true,"VM"],
  ["3294","Ethiopian Airlines","Transportation services",true,"VM"],
  ["3295","Kenya Airways","Miscellaneous shops",true,"VM"],
  ["3296","Air Berlin","Miscellaneous shops",true,"VM"],
  ["3297","Tarom Romanian Air Transport","Transportation services",true,"VM"],
  ["3298","Air Mauritius","Miscellaneous shops",true,"VM"],
  ["3299","Wideroes Flyveselskap","Miscellaneous shops",true,"VM"],
  ["3351","Affiliated Auto Rental","Miscellaneous shops",true,"VM"],
  ["3352","American International","Miscellaneous shops",true,"VM"],
  ["3353","Brooks Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3354","Action Auto Rental","Miscellaneous shops",true,"VM"],
  ["3355","Sixt Car Rental","Miscellaneous shops",true,"VM"],
  ["3357","Hertz","Miscellaneous shops",true,"VM"],
  ["3359","Payless Car Rental","Miscellaneous shops",true,"VM"],
  ["3360","Snappy Car Rental","Miscellaneous shops",true,"VM"],
  ["3361","Airways","Miscellaneous shops",true,"VM"],
  ["3362","Altra Auto Rental","Miscellaneous shops",true,"VM"],
  ["3364","Agency Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3366","Budget Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3368","Holiday Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3370","Rent-A-Wreck","Miscellaneous shops",true,"VM"],
  ["3374","Accent Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3376","Ajax Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3380","Triangle Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3381","Europcar","Miscellaneous shops",true,"VM"],
  ["3385","Tropical Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3386","Showcase Rental Cars","Miscellaneous shops",true,"VM"],
  ["3387","Alamo Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3388","Merchants Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3389","Avis Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3390","Dollar Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3391","Europe By Car","Miscellaneous shops",true,"VM"],
  ["3393","National Car Rental","Miscellaneous shops",true,"VM"],
  ["3394","Kemwell Group","Miscellaneous shops",true,"VM"],
  ["3395","Thrifty Car Rental","Miscellaneous shops",true,"VM"],
  ["3396","Tilden Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3398","Econo-Car Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3400","Auto Host Rental Cars","Miscellaneous shops",true,"VM"],
  ["3405","Enterprise Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3409","General Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3412","A1 Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3414","Godfrey National","Miscellaneous shops",true,"V"],
  ["3420","Ansa International","Miscellaneous shops",true,"VM"],
  ["3421","Allstate","Miscellaneous shops",true,"VM"],
  ["3423","AVCAR","Miscellaneous shops",true,"VM"],
  ["3425","Automate","Miscellaneous shops",true,"VM"],
  ["3427","Avon Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3428","Carey","Miscellaneous shops",true,"VM"],
  ["3429","Insurance Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3430","Major Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3431","Replacement Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3432","Reserve Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3433","Ugly Duckling Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3434","USA","Miscellaneous shops",true,"VM"],
  ["3435","Value Rent-A-Car","Miscellaneous shops",true,"VM"],
  ["3436","Autohansa","Miscellaneous shops",true,"VM"],
  ["3437","Cite","Miscellaneous shops",true,"V"],
  ["3438","Interent","Miscellaneous shops",true,"VM"],
  ["3439","Milleville","Miscellaneous shops",true,"VM"],
  ["3441","Advantage Rent A Car","Miscellaneous shops",true,"VM"],
  ["3501","Holiday Inns","Miscellaneous shops",true,"VM"],
  ["3502","Best Western","Miscellaneous shops",true,"VM"],
  ["3503","Sheraton","Miscellaneous shops",true,"VM"],
  ["3504","Hilton","Miscellaneous shops",true,"VM"],
  ["3505","Trusthouse Forte","Miscellaneous shops",true,"VM"],
  ["3506","Golden Tulip","Miscellaneous shops",true,"VM"],
  ["3507","Friendship Inns International","Miscellaneous shops",true,"VM"],
  ["3508","Quality International","Miscellaneous shops",true,"VM"],
  ["3509","Marriott","Miscellaneous shops",true,"VM"],
  ["3510","Days Inns Of America","Miscellaneous shops",true,"VM"],
  ["3511","Arabella Hotels","Transportation services",true,"VM"],
  ["3512","Intercontinental","Miscellaneous shops",true,"VM"],
  ["3513","Westin Hotels","Transportation services",true,"VM"],
  ["3514","Amerisuites","Miscellaneous shops",true,"VM"],
  ["3515","Rodeway Inns International","Miscellaneous shops",true,"VM"],
  ["3516","La Quinta Motor Inns","Miscellaneous shops",true,"VM"],
  ["3517","Americana Hotels Corporation","Transportation services",true,"VM"],
  ["3518","Sol Hotels","Transportation services",true,"VM"],
  ["3519","PLM/ETAP International","Miscellaneous shops",true,"VM"],
  ["3520","Meridien","Miscellaneous shops",true,"VM"],
  ["3521","Crest Hotels","Transportation services",true,"VM"],
  ["3522","Tokyo Group","Miscellaneous shops",true,"VM"],
  ["3523","Peninsula Hotels","Transportation services",true,"VM"],
  ["3524","Welcomgroup","Miscellaneous shops",true,"VM"],
  ["3525","Dunfey Hotels","Transportation services",true,"VM"],
  ["3526","Prince Hotels","Transportation services",true,"VM"],
  ["3527","Downtowner Passport","Miscellaneous shops",true,"VM"],
  ["3528","Thunderbird/Red Lion","Miscellaneous shops",true,"VM"],
  ["3529","CP (Canadian Pacific)","Miscellaneous shops",true,"VM"],
  ["3530","Renaissance Hotels","Transportation services",true,"VM"],
  ["3531","Kauai Coconut Beach Resort","Miscellaneous shops",true,"VM"],
  ["3532","Royal Kona Resort","Miscellaneous shops",true,"VM"],
  ["3533","Park Inn by Radisson","Miscellaneous shops",true,"VM"],
  ["3534","Southern Pacific Hotel","Transportation services",true,"VM"],
  ["3535","Hilton International","Miscellaneous shops",true,"VM"],
  ["3536","AMFAC Hotels","Transportation services",true,"VM"],
  ["3537","Ana Hotels","Transportation services",true,"VM"],
  ["3538","Concorde Hotels","Transportation services",true,"VM"],
  ["3539","Summerfield Suites Hotel","Transportation services",true,"VM"],
  ["3540","Iberotel","Miscellaneous shops",true,"VM"],
  ["3541","Hotel Okura","Transportation services",true,"VM"],
  ["3542","Royal Hotels","Transportation services",true,"VM"],
  ["3543","Four Seasons","Miscellaneous shops",true,"VM"],
  ["3544","Cigahotels","Transportation services",true,"VM"],
  ["3545","Shangri-La International","Miscellaneous shops",true,"VM"],
  ["3546","Hotel Sierra","Transportation services",true,"VM"],
  ["3547","Breakers Resort","Miscellaneous shops",true,"M"],
  ["3548","Hotels Melia","Transportation services",true,"VM"],
  ["3549","Auberge Des Governeurs","Miscellaneous shops",true,"VM"],
  ["3550","Regal 8 Inns","Miscellaneous shops",true,"VM"],
  ["3551","Mirage Hotel and Casino","Transportation services",true,"VM"],
  ["3552","Coast Hotels","Transportation services",true,"VM"],
  ["3553","Parks Inns International","Miscellaneous shops",true,"VM"],
  ["3554","Pinehurst Resort","Miscellaneous shops",true,"VM"],
  ["3555","Treasure Island Hotel and Casino","Transportation services",true,"VM"],
  ["3556","Barton Creek Resort","Miscellaneous shops",true,"VM"],
  ["3557","Manhattan East Suite Hotels","Transportation services",true,"VM"],
  ["3558","Jolly Hotels","Transportation services",true,"VM"],
  ["3559","Candlewood Suites","Miscellaneous shops",true,"VM"],
  ["3560","Aladdin Resort and Casino","Miscellaneous shops",true,"VM"],
  ["3561","Golden Nugget","Miscellaneous shops",true,"VM"],
  ["3562","Comfort Hotel International","Transportation services",true,"VM"],
  ["3563","Journeys End Motels","Miscellaneous shops",true,"VM"],
  ["3564","Sams Town Hotel and Casino","Transportation services",true,"VM"],
  ["3565","Relax Inns","Miscellaneous shops",true,"VM"],
  ["3566","Garden Place Hotel","Transportation services",true,"VM"],
  ["3567","Soho Grand Hotel","Transportation services",true,"VM"],
  ["3568","Ladbroke Hotels","Transportation services",true,"VM"],
  ["3569","Tribeca Grand Hotel","Transportation services",true,"VM"],
  ["3570","Grand Met Forum Hotels","Transportation services",true,"VM"],
  ["3571","Grand Wailea Resort","Miscellaneous shops",true,"VM"],
  ["3572","Miyako Hotel/Kintetsu","Transportation services",true,"VM"],
  ["3573","Sandman Hotels","Transportation services",true,"VM"],
  ["3574","Venture Inn","Miscellaneous shops",true,"VM"],
  ["3575","Vagabond Hotels","Transportation services",true,"VM"],
  ["3576","La Quinta Resort","Miscellaneous shops",true,"VM"],
  ["3577","Mandarin International","Miscellaneous shops",true,"VM"],
  ["3578","Frankenmuth Bavarian","Miscellaneous shops",true,"VM"],
  ["3579","Hotel Mercure","Transportation services",true,"VM"],
  ["3580","Hotel Del Coronado","Transportation services",true,"VM"],
  ["3581","Delta Hotels","Transportation services",true,"VM"],
  ["3582","California Hotel and Casino","Transportation services",true,"VM"],
  ["3583","Radisson BLU","Miscellaneous shops",true,"VM"],
  ["3584","Princess Hotels International","Transportation services",true,"VM"],
  ["3585","Hungar Hotels","Transportation services",true,"VM"],
  ["3586","Sokos Hotel","Transportation services",true,"VM"],
  ["3587","Doral Hotels","Transportation services",true,"VM"],
  ["3588","Helmsley Hotels","Transportation services",true,"VM"],
  ["3589","Doral Golf Resort","Miscellaneous shops",true,"VM"],
  ["3590","Fairmont Hotels Corporation","Transportation services",true,"VM"],
  ["3591","Sonesta International Hotels","Transportation services",true,"VM"],
  ["3592","Omni International","Miscellaneous shops",true,"VM"],
  ["3593","Cunard Hotels","Transportation services",true,"VM"],
  ["3594","Arizona Biltmore","Miscellaneous shops",true,"VM"],
  ["3595","Hospitality Inns","Professional services and membership organizations",true,"VM"],
  ["3596","Wynn Las Vegas","Miscellaneous shops",true,"VM"],
  ["3597","Riverside Resort and Casino","Miscellaneous shops",true,"VM"],
  ["3598","Regent Hotels","Transportation services",true,"VM"],
  ["3599","Pannonia Hotels","Transportation services",true,"VM"],
  ["3600","Saddlebrook Resort–Tampa","Miscellaneous shops",true,"VM"],
  ["3601","Tradewinds Resort","Miscellaneous shops",true,"VM"],
  ["3602","Hudson Hotel","Transportation services",true,"VM"],
  ["3603","Noahs Hotel (Melbourne)","Transportation services",true,"VM"],
  ["3604","Hilton Garden Inn","Miscellaneous shops",true,"VM"],
  ["3605","Jurys Doyle Hotel Group","Transportation services",true,"M"],
  ["3606","Jefferson Hotel","Transportation services",true,"M"],
  ["3607","Fontainebleau Resort","Miscellaneous shops",true,"VM"],
  ["3608","Gaylord Opryland","Miscellaneous shops",true,"VM"],
  ["3609","Gaylord Palms","Miscellaneous shops",true,"VM"],
  ["3610","Gaylord Texan","Miscellaneous shops",true,"M"],
  ["3611","C MON INN","Miscellaneous shops",true,"M"],
  ["3612","Moevenpick","Miscellaneous shops",true,"VM"],
  ["3613","Microtel Inn and Suites","Miscellaneous shops",true,"VM"],
  ["3614","AmericInn","Miscellaneous shops",true,"VM"],
  ["3615","Travelodge Motels","Transportation services",true,"VM"],
  ["3616","Hermitage Hotels","Transportation services",true,"M"],
  ["3617","America’s Best Value Inn","Miscellaneous shops",true,"VM"],
  ["3618","Great Wolf","Miscellaneous shops",true,"VM"],
  ["3619","Aloft","Miscellaneous shops",true,"VM"],
  ["3620","Binions Horseshoe Club","Retail outlet services",true,"VM"],
  ["3621","Extended Stay","Miscellaneous shops",true,"VM"],
  ["3622","Merlin Hotel (Perth)","Transportation services",true,"VM"],
  ["3623","Dorint Hotels","Transportation services",true,"VM"],
  ["3624","Lady Luck Hotel and Casino","Transportation services",true,"VM"],
  ["3625","Hotel Universal","Transportation services",true,"VM"],
  ["3626","Studio Plus","Miscellaneous shops",true,"VM"],
  ["3627","Extended Stay America","Miscellaneous shops",true,"VM"],
  ["3628","Excalibur Hotel and Casino","Transportation services",true,"VM"],
  ["3629","Dan Hotels","Transportation services",true,"VM"],
  ["3630","Extended Stay Deluxe","Miscellaneous shops",true,"VM"],
  ["3631","Sleep Inn","Miscellaneous shops",true,"VM"],
  ["3632","The Phoenician","Miscellaneous shops",true,"VM"],
  ["3633","Rank Hotels","Transportation services",true,"VM"],
  ["3634","Swissotel","Miscellaneous shops",true,"VM"],
  ["3635","Reso Hotels","Transportation services",true,"VM"],
  ["3636","Sarova Hotels","Transportation services",true,"VM"],
  ["3637","Ramada Inns","Miscellaneous shops",true,"VM"],
  ["3638","Howard Johnson","Miscellaneous shops",true,"VM"],
  ["3639","Mount Charlotte Hotels","Transportation services",true,"VM"],
  ["3640","Hyatt Hotels/International","Transportation services",true,"VM"],
  ["3641","Sofitel Hotels","Transportation services",true,"VM"],
  ["3642","Novotel Sieh (Accor)","Miscellaneous shops",true,"VM"],
  ["3643","Steigenberger","Miscellaneous shops",true,"VM"],
  ["3644","Econo-Travel Motor Hotel","Transportation services",true,"VM"],
  ["3645","Queens Moat Houses","Miscellaneous shops",true,"VM"],
  ["3646","Swallow Hotels","Transportation services",true,"VM"],
  ["3647","Grupo Hotels HUSA SA","Transportation services",true,"VM"],
  ["3648","De Vere Hotels","Transportation services",true,"VM"],
  ["3649","Radisson","Miscellaneous shops",true,"VM"],
  ["3650","Red Roof Inns","Miscellaneous shops",true,"VM"],
  ["3651","Imperial London Hotels","Transportation services",true,"VM"],
  ["3652","Embassy Hotels","Transportation services",true,"VM"],
  ["3653","Penta Hotels","Transportation services",true,"VM"],
  ["3654","Loews Hotels","Transportation services",true,"VM"],
  ["3655","Scandic Hotels","Transportation services",true,"VM"],
  ["3656","Sara Hotels","Transportation services",true,"VM"],
  ["3657","Oberoi Hotels","Transportation services",true,"VM"],
  ["3658","New Otani Hotels","Transportation services",true,"VM"],
  ["3659","Taj Hotels Intl","Transportation services",true,"VM"],
  ["3660","Knights Inn","Miscellaneous shops",true,"VM"],
  ["3661","Metropole Hotels","Transportation services",true,"VM"],
  ["3662","Circus Circus Hotel and Casino","Transportation services",true,"VM"],
  ["3663","Hoteles El Presidente","Transportation services",true,"VM"],
  ["3664","Flag Inns","Miscellaneous shops",true,"VM"],
  ["3665","Hampton Inns","Miscellaneous shops",true,"VM"],
  ["3666","Stakis Hotels","Transportation services",true,"VM"],
  ["3667","Luxor Hotel and Casino","Transportation services",true,"VM"],
  ["3668","Maritim","Miscellaneous shops",true,"VM"],
  ["3669","Eldorado Hotel and Casino","Transportation services",true,"VM"],
  ["3670","Arcade","Miscellaneous shops",true,"VM"],
  ["3671","Arctia","Miscellaneous shops",true,"VM"],
  ["3672","Campanile","Miscellaneous shops",true,"VM"],
  ["3673","Ibusz Hotels","Transportation services",true,"VM"],
  ["3674","Rantasipi Hotels","Transportation services",true,"VM"],
  ["3675","Interhotel Cedok","Transportation services",true,"VM"],
  ["3676","Monte Carlo Hotel and Casino","Transportation services",true,"VM"],
  ["3677","Climat De France","Miscellaneous shops",true,"VM"],
  ["3678","Cumulus Hotels","Transportation services",true,"VM"],
  ["3679","Silver Legacy Hotel and Casino","Transportation services",true,"VM"],
  ["3680","Hoteis Othan","Miscellaneous shops",true,"VM"],
  ["3681","Adams Mark","Miscellaneous shops",true,"VM"],
  ["3682","Sahara Hotel and Casino","Transportation services",true,"VM"],
  ["3683","Bradbury Suites","Miscellaneous shops",true,"VM"],
  ["3684","Budget Host Inns","Miscellaneous shops",true,"VM"],
  ["3685","Budgetel","Miscellaneous shops",true,"VM"],
  ["3686","Suisse Chalet","Miscellaneous shops",true,"VM"],
  ["3687","Clarion Hotel","Transportation services",true,"VM"],
  ["3688","Compri Hotel","Transportation services",true,"VM"],
  ["3689","Consort","Miscellaneous shops",true,"VM"],
  ["3690","Courtyard by Marriott","Miscellaneous shops",true,"VM"],
  ["3691","Dillon Inn","Miscellaneous shops",true,"VM"],
  ["3692","Doubletree","Miscellaneous shops",true,"VM"],
  ["3693","Drury Inn","Miscellaneous shops",true,"VM"],
  ["3694","Economy Inns Of America","Miscellaneous shops",true,"VM"],
  ["3695","Embassy Suites","Miscellaneous shops",true,"VM"],
  ["3696","Excel Inn","Miscellaneous shops",true,"VM"],
  ["3697","Fairfield Hotel","Transportation services",true,"VM"],
  ["3698","Harley Hotel","Transportation services",true,"VM"],
  ["3699","Midway Motor Lodge","Miscellaneous shops",true,"VM"],
  ["3700","Motel 6","Miscellaneous shops",true,"VM"],
  ["3701","La Mansion Del Rio","Miscellaneous shops",true,"VM"],
  ["3702","Registry Hotels","Transportation services",true,"VM"],
  ["3703","Residence Inn","Miscellaneous shops",true,"VM"],
  ["3704","Royce Hotel","Transportation services",true,"VM"],
  ["3705","Sandman Inn","Miscellaneous shops",true,"VM"],
  ["3706","Shilo Inn","Miscellaneous shops",true,"VM"],
  ["3707","Shoneys Inn","Miscellaneous shops",true,"VM"],
  ["3708","Virgin River Hotel and Casino","Transportation services",true,"VM"],
  ["3709","Super 8 Motel","Miscellaneous shops",true,"VM"],
  ["3710","Ritz-Carlton","Miscellaneous shops",true,"VM"],
  ["3711","Flag Inns (Australia)","Miscellaneous shops",true,"VM"],
  ["3712","Buffalo Bills Hotel and Casino","Transportation services",true,"VM"],
  ["3713","Quality Pacific Hotel","Transportation services",true,"VM"],
  ["3714","Four Seasons (Australia)","Miscellaneous shops",true,"VM"],
  ["3715","Fairfield Inn","Miscellaneous shops",true,"VM"],
  ["3716","Carlton Hotels","Transportation services",true,"VM"],
  ["3717","City Lodge Hotels","Transportation services",true,"VM"],
  ["3718","Karos Hotels","Transportation services",true,"VM"],
  ["3719","Protea Hotels","Transportation services",true,"VM"],
  ["3720","Southern Sun Hotels","Transportation services",true,"VM"],
  ["3721","Conrad Hotels","Transportation services",true,"VM"],
  ["3722","Wyndham","Transportation services",true,"VM"],
  ["3723","Rica Hotels","Transportation services",true,"VM"],
  ["3724","Inter Nor Hotels","Transportation services",true,"VM"],
  ["3725","Sea Pines Resort","Miscellaneous shops",true,"VM"],
  ["3726","Rio Suites","Miscellaneous shops",true,"VM"],
  ["3727","Broadmoor Hotel","Transportation services",true,"VM"],
  ["3728","Ballys Hotel and Casino","Transportation services",true,"VM"],
  ["3729","John Ascuagas Nugget","Miscellaneous shops",true,"VM"],
  ["3730","MGM Grand Hotel","Transportation services",true,"VM"],
  ["3731","Harrah’s Hotels and Casinos","Transportation services",true,"VM"],
  ["3732","Opryland Hotel","Transportation services",true,"VM"],
  ["3733","Boca Raton Resort","Miscellaneous shops",true,"M"],
  ["3734","Harvey Bristol Hotels","Transportation services",true,"VM"],
  ["3735","Masters Economy Inns","Miscellaneous shops",true,"VM"],
  ["3736","Colorado Belle Edgewater Resort","Miscellaneous shops",true,"VM"],
  ["3737","Riviera Hotel and Casino","Transportation services",true,"VM"],
  ["3738","Tropicana Resort and Casino","Miscellaneous shops",true,"VM"],
  ["3739","Woodside Hotels and Resorts","Transportation services",true,"VM"],
  ["3740","Towneplace Suites","Miscellaneous shops",true,"VM"],
  ["3741","Millennium Broadway Hotel","Transportation services",true,"VM"],
  ["3742","Club Med","Miscellaneous shops",true,"VM"],
  ["3743","Biltmore Hotel and Suites","Transportation services",true,"VM"],
  ["3744","Carefree Resorts","Miscellaneous shops",true,"VM"],
  ["3745","St. Regis Hotel","Transportation services",true,"VM"],
  ["3746","The Eliot Hotel","Transportation services",true,"VM"],
  ["3747","Club Corporation/Club Resorts","Miscellaneous shops",true,"VM"],
  ["3748","Wellesley Inns","Miscellaneous shops",true,"VM"],
  ["3749","Beverly Hills Hotel","Transportation services",true,"VM"],
  ["3750","Crowne Plaza Hotels","Transportation services",true,"VM"],
  ["3751","Homewood Suites","Miscellaneous shops",true,"VM"],
  ["3752","Peabody Hotels","Transportation services",true,"VM"],
  ["3753","Greenbriar Resorts","Miscellaneous shops",true,"VM"],
  ["3754","Amelia Island Plantation","Miscellaneous shops",true,"VM"],
  ["3755","Homestead","Miscellaneous shops",true,"VM"],
  ["3757","Canyon Ranch","Miscellaneous shops",true,"TSYS"],
  ["3758","Kahala Mandarin Oriental Hotel","Transportation services",true,"VM"],
  ["3759","Orchid At Mauna Lai","Miscellaneous shops",true,"VM"],
  ["3760","Halekulani Hotel/Waikiki Parc","Transportation services",true,"VM"],
  ["3761","Primadonna Hotel and Casino","Transportation services",true,"VM"],
  ["3762","Whiskey Pete’s Hotel and Casino","Transportation services",true,"VM"],
  ["3763","Chateau Elan Winery and Resort","Miscellaneous shops",true,"VM"],
  ["3764","Beau Rivage Hotel and Casino","Transportation services",true,"VM"],
  ["3765","Bellagio","Miscellaneous shops",true,"VM"],
  ["3766","Fremont Hotel and Casino","Transportation services",true,"VM"],
  ["3767","Main Street Station Hotel and Casino","Transportation services",true,"VM"],
  ["3768","Silver Star Hotel and Casino","Transportation services",true,"VM"],
  ["3769","Stratosphere Hotel and Casino","Transportation services",true,"VM"],
  ["3770","Springhill Suites","Miscellaneous shops",true,"VM"],
  ["3771","Caesars Hotel and Casino","Transportation services",true,"VM"],
  ["3772","Nemacolin Woodlands","Miscellaneous shops",true,"VM"],
  ["3773","Venetian Resort Hotel and Casino","Transportation services",true,"VM"],
  ["3774","New York-New York Hotel and Casino","Transportation services",true,"VM"],
  ["3775","Sands Resort","Miscellaneous shops",true,"VM"],
  ["3776","Nevele Grande Resort and Country Club","Miscellaneous shops",true,"VM"],
  ["3777","Mandalay Bay Resort","Miscellaneous shops",true,"VM"],
  ["3778","Four Points Hotels","Transportation services",true,"VM"],
  ["3779","W Hotels","Transportation services",true,"VM"],
  ["3780","Disneyland Resorts","Miscellaneous shops",true,"VM"],
  ["3781","Patricia Grand Resort Hotels","Transportation services",true,"VM"],
  ["3782","Rosen Hotel and Resorts","Transportation services",true,"VM"],
  ["3783","Town and Country Resort and Convention Center","Miscellaneous shops",true,"VM"],
  ["3784","First Hospitality Hotels","Transportation services",true,"VM"],
  ["3785","Outrigger Hotels and Resorts","Transportation services",true,"VM"],
  ["3786","Ohana Hotels of Hawaii","Transportation services",true,"VM"],
  ["3787","Caribe Royal Resort Suite and Villas","Miscellaneous shops",true,"VM"],
  ["3788","Ala Moana Hotel","Transportation services",true,"VM"],
  ["3789","Smugglers Notch Resort","Miscellaneous shops",true,"VM"],
  ["3790","Raffles Hotels","Transportation services",true,"VM"],
  ["3791","Staybridge Suites","Miscellaneous shops",true,"VM"],
  ["3792","Claridge Casino Hotel","Transportation services",true,"VM"],
  ["3793","The Flamingo Hotels","Transportation services",true,"VM"],
  ["3794","Grand Casino Hotels","Transportation services",true,"VM"],
  ["3795","Paris Las Vegas Hotel","Transportation services",true,"VM"],
  ["3796","Peppermill Hotel Casino","Transportation services",true,"VM"],
  ["3797","Atlantic City Hilton","Miscellaneous shops",true,"VM"],
  ["3798","Embassy Vacation Resort","Miscellaneous shops",true,"VM"],
  ["3799","Hale Koa Hotel","Transportation services",true,"VM"],
  ["3800","Homestead Suites","Miscellaneous shops",true,"VM"],
  ["3801","Wilderness Hotel and Resort","Transportation services",true,"VM"],
  ["3802","The Palace Hotel","Transportation services",true,"VM"],
  ["3803","The Wigwam Golf Resort and Spa","Miscellaneous shops",true,"M"],
  ["3804","The Diplomat Country Club and Spa","Miscellaneous shops",true,"M"],
  ["3805","The Atlantic","Miscellaneous shops",true,"M"],
  ["3806","Princeville Resort","Miscellaneous shops",true,"M"],
  ["3807","Element","Miscellaneous shops",true,"VM"],
  ["3808","LXR (Luxury Resorts)","Miscellaneous shops",true,"VM"],
  ["3809","Settle Inn","Miscellaneous shops",true,"M"],
  ["3810","La Costa Resort","Miscellaneous shops",true,"M"],
  ["3811","Premier Travel Inns","Transportation services",true,"VM"],
  ["3812","Hyatt Place","Miscellaneous shops",true,"VM"],
  ["3813","Hotel Indigo","Transportation services",true,"VM"],
  ["3814","The Roosevelt Hotel NY","Transportation services",true,"VM"],
  ["3815","Nickelodeon Family Suites by Holiday Inn","Miscellaneous shops",true,"VM"],
  ["3816","Home2Suites","Miscellaneous shops",true,"VM"],
  ["3817","Affinia","Miscellaneous shops",true,"M"],
  ["3818","Mainstay Suites","Miscellaneous shops",true,"VM"],
  ["3819","Oxford Suites","Miscellaneous shops",true,"VM"],
  ["3820","Jumeirah Essex House","Miscellaneous shops",true,"VM"],
  ["3821","Caribe Royal","Miscellaneous shops",true,"VM"],
  ["3822","Crossland","Miscellaneous shops",true,"VM"],
  ["3823","Grand Sierra Resort","Miscellaneous shops",true,"VM"],
  ["3824","Aria","Miscellaneous shops",true,"VM"],
  ["3825","Vdara","Miscellaneous shops",true,"VM"],
  ["3826","Autograph","Miscellaneous shops",true,"VM"],
  ["3827","Galt House","Miscellaneous shops",true,"VM"],
  ["3828","Cosmopolitan of Las Vegas","Miscellaneous shops",true,"VM"],
  ["3829","Country Inn By Carlson","Miscellaneous shops",true,"VM"],
  ["3830","Park Plaza Hotel","Transportation services",true,"VM"],
  ["3831","Waldorf","Miscellaneous shops",true,"VM"],
  ["4011","Railroads–Freight","Miscellaneous shops",true,"VM"],
  ["4111","Transportation–Suburban and Local Commuter Passenger, including Ferries","Transportation services",true,"VM"],
  ["4112","Passenger Railways","Transportation services",true,"VM"],
  ["4119","Ambulance Services","Miscellaneous shops",true,"VM"],
  ["4121","Taxicabs and Limousines","Transportation services",true,"VM"],
  ["4131","Bus Lines","Transportation services",true,"VM"],
  ["4214","Motor Freight Carriers,Trucking–Local/Long Distance, Moving and Storage Companies, Local Delivery","Miscellaneous shops",true,"VM"],
  ["4215","Courier Services–Air and Ground, Freight Forwarders","Miscellaneous shops",true,"VM"],
  ["4225","Public Warehousing–Farm Products, Refrigerated Goods, Household Goods Storage","Miscellaneous shops",true,"VM"],
  ["4411","Cruise Lines","Transportation services",true,"VM"],
  ["4457","Boat Leases and Boat Rentals","Miscellaneous shops",true,"VM"],
  ["4468","Marinas, Marine Service/Supplies","Miscellaneous shops",true,"VM"],
  ["4511","Air Carriers, Airlines–not elsewhere classified","Transportation services",true,"VM"],
  ["4582","Airports, Airport Terminals, Flying Fields","Miscellaneous shops",true,"VM"],
  ["4722","Travel Agencies and Tour Operators","Transportation services",true,"VM"],
  ["4723","Package Tour Operators (Germany Only)","Miscellaneous shops",true,"V"],
  ["4761","Telemarketing of Travel Related Services and Vitamins","Transportation services",true,"TSYS"],
  ["4784","Bridge and Road Fees, Tolls","Transportation services",true,"VM"],
  ["4789","Transportation Services Not Elsewhere Classified","Transportation services",true,"VM"],
  ["4812","Telecommunication Equipment Including Telephone Sales","Utility services",true,"VM"],
  ["4813","Key-Entry Telecom Merchant providing single local and long-distance phone calls using a central access number in a non-face-to-face environment using key entry","Miscellaneous shops",true,"M"],
  ["4814","Telecommunication Services including but not limited to prepaid phone services and recurring phone services","Utility services",true,"VM"],
  ["4816","Computer Network/Information Services","Business services",true,"VM"],
  ["4821","Telegraph Services","Miscellaneous shops",true,"VM"],
  ["4829","Wire Transfer Money Orders (V, D, G, X); Money Transfer (M)","Miscellaneous shops",true,"VM"],
  ["4899","Cable, Satellite, and Other Pay Television and Radio Services","Utility services",true,"VM"],
  ["4900","Utilities–Electric, Gas, Heating Oil, Sanitary, Water","Utility services",true,"VM"],
  ["5013","Motor Vehicle Supplies and New Parts","Miscellaneous shops",true,"VM"],
  ["5021","Office and Commercial Furniture","Miscellaneous shops",true,"VM"],
  ["5039","Construction Materials Not Elsewhere Classified","Miscellaneous shops",true,"VM"],
  ["5044","Office, Photographic, Photocopy and Microfilm Equipment","Miscellaneous shops",true,"VM"],
  ["5045","Computers, Computer Peripheral Equipment, Software","Business services",true,"VM"],
  ["5046","Commercial Equipment Not Elsewhere Classified","Miscellaneous shops",true,"VM"],
  ["5047","Dental/Laboratory/Medical/Ophthalmic Hospital Equipment and Supplies","Professional services and membership organizations",true,"VM"],
  ["5051","Metal Service Centers and Offices","Miscellaneous shops",true,"VM"],
  ["5065","Electrical Parts and Equipment","Miscellaneous shops",true,"VM"],
  ["5072","Hardware Equipment and Supplies","Miscellaneous shops",true,"VM"],
  ["5074","Plumbing and Heating Equipment","Miscellaneous shops",true,"VM"],
  ["5085","Industrial Supplies Not Elsewhere Classified","Miscellaneous shops",true,"VM"],
  ["5094","Precious Stones and Metals, Watches and Jewelry","Miscellaneous shops",true,"VM"],
  ["5099","Durable Goods Not Elsewhere Classified","Miscellaneous shops",true,"VM"],
  ["5111","Stationery, Office Supplies, Printing and Writing Paper","Miscellaneous shops",true,"VM"],
  ["5122","Drugs, Drug Proprietors and Druggists Sundries","Miscellaneous shops",true,"VM"],
  ["5131","Piece Goods, Notions, and Other Dry Goods","Miscellaneous shops",true,"VM"],
  ["5137","Men’s, Women’s and Children’s Uniforms and Commercial Clothing","Retail outlet services",true,"VM"],
  ["5139","Commercial Footware","Miscellaneous shops",true,"VM"],
  ["5169","Chemicals and Allied Products Not Elsewhere Classified","Miscellaneous shops",true,"VM"],
  ["5172","Petroleum and Petroleum Products","Miscellaneous shops",true,"VM"],
  ["5192","Books, Periodicals and Newspapers","Professional services and membership organizations",true,"VM"],
  ["5193","Florists Supplies, Nursery Stock and Flowers","Miscellaneous shops",true,"VM"],
  ["5198","Paints, Varnishes and Supplies","Miscellaneous shops",true,"VM"],
  ["5199","Non-Durable Goods Not Elsewhere Classified","Miscellaneous shops",true,"VM"],
  ["5200","Home Supply Warehouse Stores","Retail outlet services",true,"VM"],
  ["5211","Building Materials, Lumber Stores","Retail outlet services",true,"VM"],
  ["5231","Glass, Paint, Wallpaper Stores","Retail outlet services",true,"VM"],
  ["5251","Hardware Stores","Retail outlet services",true,"VM"],
  ["5261","Lawn and Garden Supply Stores","Retail outlet services",true,"VM"],
  ["5271","Mobile Home Dealers","Miscellaneous shops",true,"VM"],
  ["5299","Warehouse Club Gas","Miscellaneous shops",true,"TSYS"],
  ["5300","Wholesale Clubs","Retail outlet services",true,"VM"],
  ["5309","Duty Free Stores","Retail outlet services",true,"VM"],
  ["5310","Discount Stores","Retail outlet services",true,"VM"],
  ["5311","Department Stores","Retail outlet services",true,"VM"],
  ["5331","Variety Stores","Retail outlet services",true,"VM"],
  ["5399","Miscellaneous General Merchandise Stores","Retail outlet services",true,"VM"],
  ["5411","Grocery Stores, Supermarkets","Retail outlet services",true,"VM"],
  ["5422","Freezer and Locker Meat Provisioners","Miscellaneous shops",true,"VM"],
  ["5441","Candy, Nut and Confectionery Stores","Retail outlet services",true,"VM"],
  ["5451","Dairy Products Stores","Retail outlet services",true,"VM"],
  ["5462","Bakeries","Miscellaneous shops",true,"VM"],
  ["5499","Miscellaneous Food Stores–Convenience Stores, Markets, Specialty Stores, and Vending Machines","Retail outlet services",true,"VM"],
  ["5511","Automobile and Truck Dealers–Sales, Service, Repairs, Parts and Leasing","Miscellaneous shops",true,"VM"],
  ["5521","Automobile and Truck Dealers–(Used Only)–Sales","Miscellaneous shops",true,"VM"],
  ["5532","Automotive Tire Stores","Retail outlet services",true,"VM"],
  ["5533","Automotive Parts and Accessories Stores","Retail outlet services",true,"VM"],
  ["5541","Service Stations (With or Without Ancillary Services)","Transportation services",true,"VM"],
  ["5542","Fuel Dispenser, Automated","Miscellaneous shops",true,"VM"],
  ["5551","Boat Dealers","Miscellaneous shops",true,"VM"],
  ["5561","Camper Dealers, Recreational and Utility Trailers","Miscellaneous shops",true,"VM"],
  ["5571","Motorcycle Shops and Dealers","Retail outlet services",true,"VM"],
  ["5592","Motor Home Dealers","Miscellaneous shops",true,"VM"],
  ["5598","Snowmobile Dealers","Miscellaneous shops",true,"VM"],
  ["5599","Miscellaneous Automotive, Aircraft, and Farm Equipment Dealers–Not Elsewhere Classified","Miscellaneous shops",true,"VM"],
  ["5611","Men’s and Boys’ Clothing and Accessories Stores","Retail outlet services",true,"VM"],
  ["5621","Women’s Ready to Wear Stores","Retail outlet services",true,"VM"],
  ["5631","Women’s Accessory and Specialty Stores","Retail outlet services",true,"VM"],
  ["5641","Children’s and Infants’ Wear Stores","Retail outlet services",true,"VM"],
  ["5651","Family Clothing Stores","Retail outlet services",true,"VM"],
  ["5655","Sports Apparel, and Riding Apparel Stores","Miscellaneous shops",true,"VM"],
  ["5661","Shoe Stores","Retail outlet services",true,"VM"],
  ["5681","Furriers and Fur Shops","Retail outlet services",true,"VM"],
  ["5691","Men’s and Women’s Clothing Stores","Retail outlet services",true,"VM"],
  ["5697","Alterations, Mending, Seamstresses, Tailors","Miscellaneous shops",true,"VM"],
  ["5698","Wig and Toupee Shops","Retail outlet services",true,"VM"],
  ["5699","Accessory and Apparel Stores–Miscellaneous","Retail outlet services",true,"VM"],
  ["5712","Equipment, Furniture and Home Furnishings Stores (except Appliances)","Retail outlet services",true,"VM"],
  ["5713","Floor Covering Stores","Retail outlet services",true,"VM"],
  ["5714","Drapery, Upholstery and Window Coverings Stores","Retail outlet services",true,"VM"],
  ["5718","Fireplace, Fireplace Screens and Accessories Stores","Retail outlet services",true,"VM"],
  ["5719","Miscellaneous House Furnishing Specialty Shops","Retail outlet services",true,"VM"],
  ["5722","Household Appliance Stores","Retail outlet services",true,"VM"],
  ["5732","Electronics Sales","Business services",true,"VM"],
  ["5733","Music Stores–Musical Instruments, Pianos and Sheet Music","Retail outlet services",true,"VM"],
  ["5734","Computer Software Stores","Business services",true,"VM"],
  ["5735","Record Shops","Retail outlet services",true,"VM"],
  ["5811","Caterers","Miscellaneous shops",true,"VM"],
  ["5812","Eating Places and Restaurants","Retail outlet services",true,"VM"],
  ["5813","Bars, Cocktail Lounges, Discotheques, Nightclubs and Taverns–Drinking Places (Alcoholic Beverages)","Retail outlet services",true,"VM"],
  ["5814","Fast Food Restaurants","Retail outlet services",true,"VM"],
  ["5815","Digital Goods: Books, Movies, Music","Business services",true,"VM"],
  ["5816","Digital Goods: Games","Business services",true,"VM"],
  ["5817","Digital Goods: Applications (Excludes Games)","Business services",true,"VM"],
  ["5818","Digital Goods: Large Digital Goods Merchant (V); Digital Goods: Multi-Category (M)","Business services",true,"VM"],
  ["5912","Drug Stores and Pharmacies","Professional services and membership organizations",true,"VM"],
  ["5921","Package Stores–Beer, Wine and Liquor","Retail outlet services",true,"VM"],
  ["5931","Second Hand Stores, Used Merchandise Stores","Retail outlet services",true,"VM"],
  ["5932","Antique Shops–Sales, Repairs and Restoration Services","Retail outlet services",true,"VM"],
  ["5933","Pawn Shops","Retail outlet services",true,"VM"],
  ["5935","Wrecking and Salvage Yards","Miscellaneous shops",true,"VM"],
  ["5937","Antique Reproduction Stores","Retail outlet services",true,"VM"],
  ["5940","Bicycle Shops–Sales and Service","Retail outlet services",true,"VM"],
  ["5941","Sporting Goods Stores","Retail outlet services",true,"VM"],
  ["5942","Book Stores","Professional services and membership organizations",true,"VM"],
  ["5943","Office, School Supply and Stationery Stores","Retail outlet services",true,"VM"],
  ["5944","Clock, Jewelry, Watch and Silverware Stores","Retail outlet services",true,"VM"],
  ["5945","Game, Toy and Hobby Shops","Retail outlet services",true,"VM"],
  ["5946","Camera and Photographic Supply Stores","Retail outlet services",true,"VM"],
  ["5947","Card, Gift, Novelty and Souvenir Shops","Retail outlet services",true,"VM"],
  ["5948","Leather Goods and Luggage Stores","Retail outlet services",true,"VM"],
  ["5949","Fabric, Needlework, Piece Goods and Sewing Stores","Retail outlet services",true,"VM"],
  ["5950","Crystal and Glassware Stores","Retail outlet services",true,"VM"],
  ["5960","Direct Marketing Insurance Services","Miscellaneous shops",true,"VM"],
  ["5961","Mail Order Houses Including Catalog Order Stores","Retail outlet services",true,"TSYS"],
  ["5962","Direct Marketing–Travel Related Arrangement Services","Transportation services",true,"VM"],
  ["5963","Door-to-Door Sales","Miscellaneous shops",true,"VM"],
  ["5964","Direct Marketing–Catalog Merchants","Miscellaneous shops",true,"VM"],
  ["5965","Direct Marketing–Combination Catalog and Retail Merchant","Retail outlet services",true,"VM"],
  ["5966","Direct Marketing–Outbound Telemarketing Merchants","Miscellaneous shops",true,"VM"],
  ["5967","Direct Marketing–Inbound Telemarketing Merchants","Miscellaneous shops",true,"VM"],
  ["5968","Direct Marketing–Continuity/Subscription Merchants","Miscellaneous shops",true,"VM"],
  ["5969","Direct Marketing–Other Direct Marketers–Not Elsewhere Classified","Miscellaneous shops",true,"VM"],
  ["5970","Artist Supply Stores, Craft Shops","Retail outlet services",true,"VM"],
  ["5971","Art Dealers and Galleries","Miscellaneous shops",true,"VM"],
  ["5972","Stamp and Coin Stores–Philatelic and Numismatic Supplies","Retail outlet services",true,"VM"],
  ["5973","Religious Goods Stores","Retail outlet services",true,"VM"],
  ["5974","Rubber Stamp Store","Miscellaneous shops",true,"TSYS"],
  ["5975","Hearing Aids–Sales, Service, Supply Stores","Retail outlet services",true,"VM"],
  ["5976","Orthopedic Goods–Artificial Limb Stores","Retail outlet services",true,"VM"],
  ["5977","Cosmetic Stores","Miscellaneous shops",true,"VM"],
  ["5978","Typewriter Stores–Rentals, Sales, Service","Retail outlet services",true,"VM"],
  ["5983","Fuel Dealers–Coal, Fuel Oil, Liquefied Petroleum, Wood","Miscellaneous shops",true,"VM"],
  ["5992","Florists","Miscellaneous shops",true,"VM"],
  ["5993","Cigar Stores and Stands","Retail outlet services",true,"VM"],
  ["5994","News Dealers and Newsstands","Miscellaneous shops",true,"VM"],
  ["5995","Pet Shops, Pet Food and Supplies","Retail outlet services",true,"VM"],
  ["5996","Swimming Pools–Sales and Supplies","Miscellaneous shops",true,"VM"],
  ["5997","Electric Razor Stores–Sales and Service","Retail outlet services",true,"VM"],
  ["5998","Tent and Awning Shops","Retail outlet services",true,"VM"],
  ["5999","Miscellaneous and Specialty Retail Stores","Retail outlet services",true,"VM"],
  ["6010","Member Financial Institution–Manual Cash Disbursements","Miscellaneous shops",true,"VM"],
  ["6011","Member Financial Institution–Automated Cash Disbursements","Miscellaneous shops",true,"VM"],
  ["6012","Member Financial Institution–Merchandise And Services","Miscellaneous shops",true,"VM"],
  ["6050","Quasi Cash–Member Financial Institution","Miscellaneous shops",true,"M"],
  ["6051","Quasi Cash–Merchant","Miscellaneous shops",true,"VM"],
  ["6211","Securities–Brokers and Dealers","Miscellaneous shops",true,"VM"],
  ["6236","Aero Servicio Carabobo","Miscellaneous shops",true,"TSYS"],
  ["6300","Insurance Sales, Underwriting and Premiums","Miscellaneous shops",true,"VM"],
  ["6381","Insurance–Premiums","Miscellaneous shops",true,"TSYS"],
  ["6513","Real Estate Agents and Managers–Rentals","Miscellaneous shops",true,"VM"],
  ["6529","Remote Stored Value Load — Member Financial Institution","Miscellaneous shops",true,"TSYS"],
  ["6530","Remove Stored Value Load — Merchant","Miscellaneous shops",true,"TSYS"],
  ["6535","Value Purchase–Member Financial Institution","Miscellaneous shops",true,"TSYS"],
  ["6536","MoneySend Intracountry","Miscellaneous shops",true,"M"],
  ["6537","MoneySend Intercountry","Miscellaneous shops",true,"M"],
  ["6538","MoneySend Funding","Miscellaneous shops",true,"M"],
  ["6539","Funding Transaction (Excluding MoneySend)","Miscellaneous shops",true,"M"],
  ["6540","POI (Point of Interaction) Funding Transactions (Excluding MoneySend)","Miscellaneous shops",true,"M"],
  ["6611","Overpayments","Miscellaneous shops",true,"TSYS"],
  ["6760","Savings Bonds","Miscellaneous shops",true,"TSYS"],
  ["7011","Lodging–Hotels, Motels, Resorts–not elsewhere classified","Transportation services",true,"VM"],
  ["7012","Timeshares","Miscellaneous shops",true,"VM"],
  ["7032","Sporting and Recreational Camps","Miscellaneous shops",true,"VM"],
  ["7033","Campgrounds and Trailer Parks","Miscellaneous shops",true,"VM"],
  ["7210","Cleaning, Garment and Laundry Services","Miscellaneous shops",true,"VM"],
  ["7211","Laundry Services–Family and Commercial","Miscellaneous shops",true,"VM"],
  ["7216","Dry Cleaners","Miscellaneous shops",true,"VM"],
  ["7217","Carpet and Upholstery Cleaning","Miscellaneous shops",true,"VM"],
  ["7221","Photographic Studios","Miscellaneous shops",true,"VM"],
  ["7230","Barber and Beauty Shops","Miscellaneous shops",true,"VM"],
  ["7251","Hat Cleaning Shops, Shoe Repair Shops, Shoe Shine Parlors","Retail outlet services",true,"VM"],
  ["7261","Funeral Service and Crematories","Miscellaneous shops",true,"VM"],
  ["7273","Dating Services","Miscellaneous shops",true,"VM"],
  ["7276","Tax Preparation Service","Miscellaneous shops",true,"VM"],
  ["7277","Debt, Marriage, Personal–Counseling Services","Miscellaneous shops",true,"VM"],
  ["7278","Buying/Shopping Clubs, Services","Miscellaneous shops",true,"VM"],
  ["7280","Hospital Patient-Personal Funds Withdrawal","Professional services and membership organizations",true,"TSYS"],
  ["7295","Babysitting Services","Miscellaneous shops",true,"TSYS"],
  ["7296","Clothing Rental–Costumes, Uniforms and Formal Wear","Retail outlet services",true,"VM"],
  ["7297","Massage Parlors","Miscellaneous shops",true,"VM"],
  ["7298","Health and Beauty Spas","Miscellaneous shops",true,"VM"],
  ["7299","Other Services–Not Elsewhere Classified","Miscellaneous shops",true,"VM"],
  ["7311","Advertising Services","Miscellaneous shops",true,"VM"],
  ["7321","Consumer Credit Reporting Agencies","Miscellaneous shops",true,"VM"],
  ["7332","Blueprinting and Photocopying Services","Miscellaneous shops",true,"TSYS"],
  ["7333","Commercial Art, Graphics, Photography","Miscellaneous shops",true,"VM"],
  ["7338","Quick Copy, Reproduction and Blueprinting Services","Miscellaneous shops",true,"VM"],
  ["7339","Stenographic and Secretarial Support Services","Miscellaneous shops",true,"VM"],
  ["7342","Exterminating and Disinfecting Services","Miscellaneous shops",true,"VM"],
  ["7349","Cleaning and Maintenance, Janitorial Services","Miscellaneous shops",true,"VM"],
  ["7361","Employment Agencies and Temporary Help Services","Miscellaneous shops",true,"VM"],
  ["7372","Computer Programming, Data Processing and Integrated System Design Services","Business services",true,"VM"],
  ["7375","Information Retrieval Services","Miscellaneous shops",true,"VM"],
  ["7379","Computer Maintenance, Repair And Services–Not Elsewhere Classified","Business services",true,"VM"],
  ["7392","Consulting, Management and Public Relations Services","Miscellaneous shops",true,"VM"],
  ["7393","Detective Agencies, Protective Agencies, Security Services including Armored Cars, Guard Dogs","Miscellaneous shops",true,"VM"],
  ["7394","Equipment Rental and Leasing Services, Furniture Rental, Tool Rental","Miscellaneous shops",true,"VM"],
  ["7395","Photo Developing, Photofinishing Laboratories","Miscellaneous shops",true,"VM"],
  ["7399","Business Services Not Elsewhere Classified","Miscellaneous shops",true,"VM"],
  ["7512","Automobile Rental Agency–Not Elsewhere Classified","Miscellaneous shops",true,"VM"],
  ["7513","Truck Rental","Miscellaneous shops",true,"VM"],
  ["7519","Motor Home and Recreational Vehicle Rental","Miscellaneous shops",true,"VM"],
  ["7523","Automobile Parking Lots and Garages","Miscellaneous shops",true,"VM"],
  ["7524","Express Payment Service Merchants–Parking Lots and Garages","Miscellaneous shops",true,"TSYS"],
  ["7531","Automotive Body Repair Shops","Retail outlet services",true,"VM"],
  ["7534","Tire Retreading and Repair Shops","Retail outlet services",true,"VM"],
  ["7535","Automotive Paint Shops","Retail outlet services",true,"VM"],
  ["7538","Automotive Service Shops","Retail outlet services",true,"VM"],
  ["7542","Car Washes","Miscellaneous shops",true,"VM"],
  ["7549","Towing Services","Miscellaneous shops",true,"VM"],
  ["7622","Electronic Repair Shops","Retail outlet services",true,"VM"],
  ["7623","Air Conditioning and Refrigeration Repair Shops","Retail outlet services",true,"VM"],
  ["7629","Appliance Repair Shops, Electrical and Small","Retail outlet services",true,"VM"],
  ["7631","Clock, Jewelry and Watch Repair Shops","Retail outlet services",true,"VM"],
  ["7641","Furniture–Reupholstery, Repair and Refinishing","Miscellaneous shops",true,"VM"],
  ["7692","Welding Repair","Miscellaneous shops",true,"VM"],
  ["7699","Miscellaneous Repair Shops and Related Services","Retail outlet services",true,"VM"],
  ["7800","Government Owned Lottery","Miscellaneous shops",true,"VM"],
  ["7801","Government-Licensed Casinos (Online or Internet Gambling)","Miscellaneous shops",true,"VM"],
  ["7802","Government-Licensed Horse/Dog Racing","Miscellaneous shops",true,"VM"],
  ["7829","Motion Picture and Video Tape Production and Distribution","Miscellaneous shops",true,"VM"],
  ["7832","Motion Picture Theaters","Miscellaneous shops",true,"VM"],
  ["7833","Express Payment Service — Motion Picture Theater","Miscellaneous shops",true,"TSYS"],
  ["7841","DVD/Video Tape Rental Stores","Retail outlet services",true,"VM"],
  ["7911","Dance Halls, Schools and Studios","Professional services and membership organizations",true,"VM"],
  ["7922","Theatrical Producers (Except Motion Pictures), Ticket Agencies","Miscellaneous shops",true,"VM"],
  ["7929","Bands, Orchestras and Miscellaneous Entertainers– Not Elsewhere Classified","Miscellaneous shops",true,"VM"],
  ["7932","Pool and Billiard Establishments","Miscellaneous shops",true,"VM"],
  ["7933","Bowling Alleys","Miscellaneous shops",true,"VM"],
  ["7941","Athletic Fields, Commercial Sports, Professional Sports Clubs, Sports Promoters","Miscellaneous shops",true,"VM"],
  ["7991","Tourist Attractions and Exhibits","Miscellaneous shops",true,"VM"],
  ["7992","Golf Courses, Public","Miscellaneous shops",true,"VM"],
  ["7993","Video Amusement Game Supplies","Miscellaneous shops",true,"VM"],
  ["7994","Video Game Arcades and Establishments","Miscellaneous shops",true,"VM"],
  ["7995","Betting (Sportsbook, fantasy, social gaming; when regulated and not covered by other MCCs) (D)","Professional services and membership organizations",true,"VM"],
  ["7996","Amusement Parks, Carnivals, Circuses, Carnivals, Fortune Tellers","Miscellaneous shops",true,"VM"],
  ["7997","Clubs–Country Clubs, Membership (Athletic, Recreation, Sports), Private Golf Courses","Miscellaneous shops",true,"VM"],
  ["7998","Aquariums, Dolphinariums, Zoos and Seaquariums","Miscellaneous shops",true,"VM"],
  ["7999","Recreation Services–Not Elsewhere Classified","Miscellaneous shops",true,"VM"],
  ["8011","Doctors–not elsewhere classified","Professional services and membership organizations",true,"VM"],
  ["8021","Dentists and Orthodontists","Professional services and membership organizations",true,"VM"],
  ["8031","Osteopathic Physicians","Miscellaneous shops",true,"VM"],
  ["8041","Chiropractors","Professional services and membership organizations",true,"VM"],
  ["8042","Optometrists and Ophthalmologists","Miscellaneous shops",true,"VM"],
  ["8043","Opticians, Optical Goods and Eyeglasses","Professional services and membership organizations",true,"VM"],
  ["8044","Optical Goods and Eyeglasses","Miscellaneous shops",true,"TSYS"],
  ["8049","Chiropodists, Podiatrists","Professional services and membership organizations",true,"VM"],
  ["8050","Nursing and Personal Care Facilities","Miscellaneous shops",true,"VM"],
  ["8062","Hospitals","Professional services and membership organizations",true,"VM"],
  ["8071","Dental and Medical Laboratories","Professional services and membership organizations",true,"VM"],
  ["8099","Health Practitioners, Medical Services–Not Elsewhere Classified","Professional services and membership organizations",true,"VM"],
  ["8111","Attorneys, Legal Services","Miscellaneous shops",true,"VM"],
  ["8211","Schools, Elementary and Secondary","Professional services and membership organizations",true,"VM"],
  ["8220","Colleges, Universities, Professional Schools and Junior Colleges","Professional services and membership organizations",true,"VM"],
  ["8241","Schools, Correspondence","Professional services and membership organizations",true,"VM"],
  ["8244","Schools, Business and Secretarial","Professional services and membership organizations",true,"VM"],
  ["8249","Schools, Trade and Vocational","Professional services and membership organizations",true,"VM"],
  ["8299","Schools And Educational Services–Not Elsewhere Classified","Professional services and membership organizations",true,"VM"],
  ["8351","Child Care Services","Miscellaneous shops",true,"VM"],
  ["8398","Organizations, Charitable and Social Service","Miscellaneous shops",true,"VM"],
  ["8641","Associations–Civic, Social and Fraternal","Miscellaneous shops",true,"VM"],
  ["8651","Organizations, Political","Miscellaneous shops",true,"VM"],
  ["8661","Organizations, Religious","Miscellaneous shops",true,"VM"],
  ["8675","Automobile Associations","Miscellaneous shops",true,"VM"],
  ["8699","Organizations, Membership–Not Elsewhere Classified","Miscellaneous shops",true,"VM"],
  ["8734","Testing Laboratories (Non-Medical)","Professional services and membership organizations",true,"VM"],
  ["8743","Testing Laboratories (Non-Medical)","Professional services and membership organizations",true,"TSYS"],
  ["8911","Architectural, Engineering and Surveying Services","Miscellaneous shops",true,"VM"],
  ["8931","Accounting, Auditing and Bookkeeping Services","Professional services and membership organizations",true,"VM"],
  ["8999","Professional Services–Not Elsewhere Classified","Miscellaneous shops",true,"VM"],
  ["9034","I-Purchasing Pilot","Miscellaneous shops",true,"TSYS"],
  ["9211","Court Costs Including Alimony and Child Support","Miscellaneous shops",true,"VM"],
  ["9222","Fines","Miscellaneous shops",true,"VM"],
  ["9223","Bail and Bond Payments","Miscellaneous shops",true,"VM"],
  ["9311","Tax Payments","Miscellaneous shops",true,"VM"],
  ["9399","Government Services–Not Elsewhere Classified","Miscellaneous shops",true,"VM"],
  ["9401","I-Purchasing Pilot","Miscellaneous shops",true,"TSYS"],
  ["9402","Postal Services–Government Only","Miscellaneous shops",true,"VM"],
  ["9405","Intra-Government Purchases–Government Only","Miscellaneous shops",true,"VM"],
  ["9700","Automated Referral Service","Miscellaneous shops",true,"V"],
  ["9701","Visa Credential Server","Miscellaneous shops",true,"V"],
  ["9702","GCAS Emergency Services","Miscellaneous shops",true,"V"],
  ["9751","UK Supermarkets, Electronic Hot File","Miscellaneous shops",true,"TSYS"],
  ["9752","UK Petrol Stations, Electronic Hot File","Miscellaneous shops",true,"TSYS"],
  ["9754","Gambling-Horse, Dog Racing, State Lottery","Miscellaneous shops",true,"M"],
  ["9950","Intra-Company Purchases","Miscellaneous shops",true,"VM"],
] as const;

export class SeedReferenceData1784783921000 implements MigrationInterface {
  name = 'SeedReferenceData1784783921000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `
        INSERT INTO "banks"
          ("swift_code", "name", "short_name")
        SELECT *
        FROM unnest(
          $1::varchar[],
          $2::varchar[],
          $3::varchar[]
        )
      `,
      [
        BANK_REFERENCE_DATA.map((bank) => bank[0]),
        BANK_REFERENCE_DATA.map((bank) => bank[1]),
        BANK_REFERENCE_DATA.map((bank) => bank[2]),
      ],
    );

    await queryRunner.query(
      `
        INSERT INTO "merchant_category_codes"
          ("code", "description", "category", "is_active", "valid_payment")
        SELECT *
        FROM unnest(
          $1::varchar[],
          $2::text[],
          $3::varchar[],
          $4::boolean[],
          $5::varchar[]
        )
        ON CONFLICT ("code") DO UPDATE SET
          "description" = EXCLUDED."description",
          "category" = EXCLUDED."category",
          "is_active" = EXCLUDED."is_active",
          "valid_payment" = EXCLUDED."valid_payment"
      `,
      [
        MCC_REFERENCE_DATA.map((mcc) => mcc[0]),
        MCC_REFERENCE_DATA.map((mcc) => mcc[1]),
        MCC_REFERENCE_DATA.map((mcc) => mcc[2]),
        MCC_REFERENCE_DATA.map((mcc) => mcc[3]),
        MCC_REFERENCE_DATA.map((mcc) => mcc[4]),
      ],
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DELETE FROM "merchant_category_codes" WHERE "code" = ANY($1::varchar[])`,
      [MCC_REFERENCE_DATA.map((mcc) => mcc[0])],
    );

    await queryRunner.query(
      `DELETE FROM "banks" WHERE "swift_code" = ANY($1::varchar[])`,
      [BANK_REFERENCE_DATA.map((bank) => bank[0])],
    );
  }
}
