-- CardPilot mobile SQLite schema v1 (review draft).
--
-- This file documents the physical schema that the Drift tables/migration must
-- create. It is not wired into the Flutter app yet. Timestamps are UTC Unix
-- epoch milliseconds. IDs are UUID strings generated by the mobile app.

PRAGMA
foreign_keys = ON;

BEGIN
IMMEDIATE;

-- Multiple cloud accounts may be retained locally, but only the profile
-- referenced by app_settings.active_profile_id is visible to product queries.
-- A guest starts with auth_user_id/server_user_id set to NULL. Claiming that
-- guest profile attaches the cloud IDs without changing this local primary key.
CREATE TABLE local_profiles
(
    id                 TEXT PRIMARY KEY NOT NULL,
    auth_user_id       TEXT,
    server_user_id     TEXT,
    access_mode        TEXT             NOT NULL
        CHECK (access_mode IN ('guest', 'authenticated')),
    email              TEXT,
    display_name       TEXT             NOT NULL
        CHECK (length(trim(display_name)) BETWEEN 1 AND 40),
    born_date_at       INTEGER,
    setup_completed_at INTEGER,
    created_at         INTEGER          NOT NULL,
    updated_at         INTEGER          NOT NULL,
    deleted_at         INTEGER,
    sync_status        TEXT             NOT NULL DEFAULT 'local_only'
        CHECK (sync_status IN (
                               'local_only', 'pending', 'synced', 'failed', 'conflict'
            )),
    server_version     INTEGER,
    last_synced_at     INTEGER,
    CHECK (server_version IS NULL OR server_version >= 1)
);

CREATE UNIQUE INDEX uq_local_profiles_auth_user
    ON local_profiles (auth_user_id) WHERE auth_user_id IS NOT NULL AND deleted_at IS NULL;

CREATE UNIQUE INDEX uq_local_profiles_server_user
    ON local_profiles (server_user_id) WHERE server_user_id IS NOT NULL AND deleted_at IS NULL;

-- Keep at most one live guest profile on an installation. Authenticated
-- profiles A, B, ... can coexist and are selected through app_settings.
CREATE UNIQUE INDEX uq_local_profiles_single_guest
    ON local_profiles (access_mode) WHERE access_mode = 'guest' AND deleted_at IS NULL;

CREATE INDEX idx_local_profiles_sync_status
    ON local_profiles (sync_status, updated_at);

-- Singleton installation settings. The application inserts id = 1 after it
-- generates installation_id. Keeping active state here avoids an is_active flag
-- racing across multiple profile rows.
CREATE TABLE app_settings
(
    id                INTEGER PRIMARY KEY NOT NULL DEFAULT 1
        CHECK (id = 1),
    installation_id   TEXT                NOT NULL UNIQUE,
    active_profile_id TEXT,
    created_at        INTEGER             NOT NULL,
    updated_at        INTEGER             NOT NULL,
    FOREIGN KEY (active_profile_id)
        REFERENCES local_profiles (id) ON DELETE SET NULL
);

-- ---------------------------------------------------------------------------
-- Shared read-only reference caches.
--
-- These rows do not carry profile_id. They are shared by every local profile.
-- Cache tables intentionally avoid cross-dataset foreign keys: each dataset is
-- versioned independently in cloud and replaced atomically after validation.
-- ---------------------------------------------------------------------------

CREATE TABLE memberships_cache
(
    id                                  TEXT PRIMARY KEY NOT NULL,
    name                                TEXT             NOT NULL,
    max_cards                           INTEGER,
    max_receipt_scans_per_month         INTEGER,
    max_cashback_calculations_per_month INTEGER,
    server_updated_at                   INTEGER,
    dataset_version                     INTEGER          NOT NULL CHECK (dataset_version >= 1)
);

CREATE UNIQUE INDEX uq_memberships_cache_name
    ON memberships_cache (name);

CREATE TABLE banks_cache
(
    id                TEXT PRIMARY KEY NOT NULL,
    swift_code        TEXT,
    name              TEXT             NOT NULL,
    short_name        TEXT,
    server_updated_at INTEGER,
    dataset_version   INTEGER          NOT NULL CHECK (dataset_version >= 1)
);

CREATE UNIQUE INDEX uq_banks_cache_swift_code
    ON banks_cache (swift_code) WHERE swift_code IS NOT NULL;

CREATE INDEX idx_banks_cache_name
    ON banks_cache (name);

CREATE INDEX idx_banks_cache_short_name
    ON banks_cache (short_name);

CREATE TABLE credit_cards_cache
(
    id                 TEXT PRIMARY KEY NOT NULL,
    bank_id            TEXT             NOT NULL,
    name               TEXT             NOT NULL,
    network            TEXT,
    card_type          TEXT             NOT NULL DEFAULT 'credit',
    annual_fee_decimal TEXT,
    source_url         TEXT,
    last_verified_at   INTEGER,
    is_active          INTEGER          NOT NULL DEFAULT 1
        CHECK (is_active IN (0, 1)),
    server_updated_at  INTEGER,
    dataset_version    INTEGER          NOT NULL CHECK (dataset_version >= 1)
);

CREATE INDEX idx_credit_cards_cache_bank_active
    ON credit_cards_cache (bank_id, is_active);

CREATE INDEX idx_credit_cards_cache_name
    ON credit_cards_cache (name);

CREATE TABLE merchant_category_codes_cache
(
    code              TEXT PRIMARY KEY NOT NULL
        CHECK (length(code) = 4),
    description       TEXT             NOT NULL,
    category          TEXT,
    valid_payment     TEXT,
    is_active         INTEGER          NOT NULL DEFAULT 1
        CHECK (is_active IN (0, 1)),
    server_updated_at INTEGER,
    dataset_version   INTEGER          NOT NULL CHECK (dataset_version >= 1)
);

CREATE INDEX idx_mcc_cache_category_active
    ON merchant_category_codes_cache (category, is_active);

CREATE TABLE reward_rules_cache
(
    id                            TEXT PRIMARY KEY NOT NULL,
    credit_card_id                TEXT             NOT NULL,
    name                          TEXT             NOT NULL,
    reward_type                   TEXT             NOT NULL,
    cashback_rate_decimal         TEXT,
    points_rate_decimal           TEXT,
    monthly_cap_amount_decimal    TEXT,
    minimum_transaction_decimal   TEXT,
    minimum_monthly_spend_decimal TEXT,
    eligible_channel              TEXT             NOT NULL DEFAULT 'any',
    conditions_text               TEXT,
    effective_from                TEXT,
    effective_to                  TEXT,
    source_url                    TEXT,
    confidence_ppm                INTEGER
        CHECK (confidence_ppm IS NULL OR confidence_ppm BETWEEN 0 AND 1000000),
    last_verified_at              INTEGER,
    is_active                     INTEGER          NOT NULL DEFAULT 1
        CHECK (is_active IN (0, 1)),
    server_updated_at             INTEGER,
    dataset_version               INTEGER          NOT NULL CHECK (dataset_version >= 1)
);

CREATE INDEX idx_reward_rules_cache_card_active
    ON reward_rules_cache (credit_card_id, is_active);

CREATE TABLE reward_rule_mccs_cache
(
    id              TEXT PRIMARY KEY NOT NULL,
    reward_rule_id  TEXT             NOT NULL,
    mcc_code        TEXT             NOT NULL CHECK (length(mcc_code) = 4),
    match_type      TEXT             NOT NULL,
    dataset_version INTEGER          NOT NULL CHECK (dataset_version >= 1),
    UNIQUE (reward_rule_id, mcc_code, match_type)
);

CREATE INDEX idx_reward_rule_mccs_cache_mcc
    ON reward_rule_mccs_cache (mcc_code);

-- ---------------------------------------------------------------------------
-- Profile-owned data.
-- ---------------------------------------------------------------------------

CREATE TABLE local_user_cards
(
    id                 TEXT PRIMARY KEY NOT NULL,
    profile_id         TEXT             NOT NULL,
    credit_card_id     TEXT,
    bank_id            TEXT,
    bank_name_snapshot TEXT             NOT NULL,
    nickname           TEXT             NOT NULL CHECK (length(trim(nickname)) > 0),
    billing_cycle_day  INTEGER          NOT NULL
        CHECK (billing_cycle_day BETWEEN 1 AND 31),
    is_default         INTEGER          NOT NULL DEFAULT 0
        CHECK (is_default IN (0, 1)),
    has_annual_fee     INTEGER          NOT NULL DEFAULT 0
        CHECK (has_annual_fee IN (0, 1)),
    created_at         INTEGER          NOT NULL,
    updated_at         INTEGER          NOT NULL,
    deleted_at         INTEGER,
    sync_status        TEXT             NOT NULL DEFAULT 'local_only'
        CHECK (sync_status IN (
                               'local_only', 'pending', 'synced', 'failed', 'conflict'
            )),
    server_version     INTEGER,
    last_synced_at     INTEGER,
    FOREIGN KEY (profile_id)
        REFERENCES local_profiles (id) ON DELETE CASCADE,
    CHECK (server_version IS NULL OR server_version >= 1)
);

CREATE INDEX idx_local_user_cards_profile_active
    ON local_user_cards (profile_id, deleted_at);

CREATE UNIQUE INDEX uq_local_user_cards_default
    ON local_user_cards (profile_id) WHERE is_default = 1 AND deleted_at IS NULL;

-- Mutation payloads are API-versioned JSON strings. They must never contain
-- Supabase access/refresh tokens or service-role credentials.
CREATE TABLE sync_outbox
(
    id                  TEXT PRIMARY KEY NOT NULL,
    profile_id          TEXT             NOT NULL,
    entity_type         TEXT             NOT NULL,
    entity_id           TEXT             NOT NULL,
    operation           TEXT             NOT NULL
        CHECK (operation IN ('create', 'update', 'delete')),
    payload_json        TEXT             NOT NULL,
    payload_version     INTEGER          NOT NULL DEFAULT 1
        CHECK (payload_version >= 1),
    base_server_version INTEGER,
    idempotency_key     TEXT             NOT NULL UNIQUE,
    attempt_count       INTEGER          NOT NULL DEFAULT 0
        CHECK (attempt_count >= 0),
    next_attempt_at     INTEGER          NOT NULL,
    last_error_code     TEXT,
    created_at          INTEGER          NOT NULL,
    FOREIGN KEY (profile_id)
        REFERENCES local_profiles (id) ON DELETE CASCADE,
    CHECK (base_server_version IS NULL OR base_server_version >= 1)
);

CREATE INDEX idx_sync_outbox_ready
    ON sync_outbox (profile_id, next_attempt_at, created_at);

-- scope examples:
--   reference:banks
--   reference:merchant_category_codes
--   profile:<local-profile-id>:user_data
CREATE TABLE sync_state
(
    scope           TEXT PRIMARY KEY NOT NULL,
    cursor          TEXT,
    dataset_version INTEGER,
    etag            TEXT,
    last_attempt_at INTEGER,
    last_success_at INTEGER,
    next_check_at   INTEGER,
    last_error_code TEXT,
    CHECK (dataset_version IS NULL OR dataset_version >= 1)
);

COMMIT;
